name: Build OBI Executable

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install pyserial pyinstaller
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed --name "OBI" main.py
    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: OBI-Executable
        path: dist/OBI.exe
